<a href="https://colab.research.google.com/github/ThomasRoa/Integracion-de-datos-2025/blob/main/Thomas_Roa__Reto_integraci%C3%B3n_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas scikit-learn scikit-learn-extra openpyxl

  Using cached scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
  Using cached scikit_learn_extra-0.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Using cached scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.5 MB)
Using cached scikit_learn_extra-0.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.13.0 requires numpy<3,>=1.24.3, but you have numpy 1.23.5 which is incompatible.


In [2]:
!pip uninstall -y numpy scikit-learn scikit-learn-extra

Found existing installation: numpy 1.23.5
Uninstalling numpy-1.23.5:
  Successfully uninstalled numpy-1.23.5
Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Found existing installation: scikit-learn-extra 0.3.0
Uninstalling scikit-learn-extra-0.3.0:
  Successfully uninstalled scikit-learn-extra-0.3.0


In [3]:
!pip install --upgrade --force-reinstall numpy==1.23.5

!pip install --upgrade --force-reinstall scikit-learn==1.2.2 scikit-learn-extra==0.3.0

  Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Using cached numpy-1.23.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pynndescent 0.5.13 requires scikit-learn>=0.18, which is not installed.
imbalanced-learn 0.13.0 requires scikit-learn<2,>=1.3.2, which is not installed.
sklearn-pandas 2.2.0 requires scikit-learn>=0.23.0, which is not installed.
mlxtend 0.23.4 requires scikit-learn>=1.3.1, which is not installed.
yellowbrick 1.5 requires scikit-learn>=1.0.0, which is not installed.
shap 0.47.1 requires scikit-learn, which is not installed.
sentence-transformers 3.4.1 requires scikit-learn, which is not installed.
fastai 2.7.19 requires scikit-learn, which is not installed.
librosa 0.11.0 requires scikit-learn>=1.1.0, which is not inst

  Using cached scikit_learn-1.2.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
  Using cached scikit_learn_extra-0.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
ERROR: Operation cancelled by user
^C


In [4]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn_extra.cluster import KMedoids
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import pairwise_distances_argmin_min

In [5]:
url = "/content/4. DB_Fintechs (USD).xlsx"
df_base = pd.read_excel(url, sheet_name='Fintech Base')
df_ext1 = pd.read_excel(url, sheet_name='Fintech Ext. 1')
df_ext2 = pd.read_excel(url, sheet_name='Fintech Ext.2')
df_ext3 = pd.read_excel(url, sheet_name='Fintech Ext.3')

In [6]:
variables = ['Edad', 'Ingresos', 'Egresos', 'Monto (EAD)']

In [7]:
scaler = StandardScaler()
data_base_scaled = scaler.fit_transform(df_base[variables])

In [8]:
kmeans = KMeans(n_clusters=5, random_state=42)
df_base['Cluster'] = kmeans.fit_predict(data_base_scaled)

print("Clusters iniciales (K-Means):", df_base['Cluster'].value_counts())
print("Centroides iniciales (K-Means):", kmeans.cluster_centers_)

/usr/local/lib/python3.11/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
Exception ignored on calling ctypes callback function: <function ThreadpoolController._find_libraries_with_dl_iterate_phdr.<locals>.match_library_callback at 0x78ac6e9cae80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/threadpoolctl.py", line 1005, in match_library_callback
    self._make_controller_from_path(filepath)
  File "/usr/local/lib/python3.11/dist-packages/threadpoolctl.py", line 1187, in _make_controller_from_path
    lib_controller = controller_class(
                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/threadpoolctl.py", line 114, in __init__
    self.dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/li

Clusters iniciales (K-Means): Cluster
4    413
1    383
0    326
2    223
3    155
Name: count, dtype: int64
Centroides iniciales (K-Means): [[ 1.08010513 -0.74345247 -0.63965516 -0.65654682]
 [-0.67672847  0.33798192  0.33168035  0.2466104 ]
 [ 0.99129851  0.67162654  0.50979952  0.62240113]
 [-0.27921294  1.97623849  1.73058035  1.78919972]
 [-0.65546932 -0.83092314 -0.72743641 -0.71801192]]


In [9]:
def integrar_y_clusterizar(df_base, df_new):
    df_integrado = pd.concat([df_base, df_new], ignore_index=True)
    datos_integrados_scaled = scaler.fit_transform(df_integrado[variables])
    kmedoids = KMedoids(n_clusters=5, random_state=42)
    df_integrado['Cluster'] = kmedoids.fit_predict(datos_integrados_scaled)
    _, distances = pairwise_distances_argmin_min(kmedoids.cluster_centers_, datos_integrados_scaled)
    sse = sum(distances**2)

    cluster_counts = df_integrado['Cluster'].value_counts()
    nuevos_clusters = df_integrado.iloc[-len(df_new):]['Cluster'].value_counts()

    print("Clusters después de integración (K-Medoids):", cluster_counts)
    print("Medoids después de integración (K-Medoids):", kmedoids.cluster_centers_)
    print("Distribución de nuevos datos por cluster:", nuevos_clusters)
    print("Variabilidad de los clusters (SSE):", sse)

    return df_integrado

In [10]:
print("\nIntegración con Ext. 1")
df_base = integrar_y_clusterizar(df_base, df_ext1)
print("\nIntegración con Ext. 2")
df_base = integrar_y_clusterizar(df_base, df_ext2)
print("\nIntegración con Ext. 3")
df_base = integrar_y_clusterizar(df_base, df_ext3)


Integración con Ext. 1
Clusters después de integración (K-Medoids): Cluster
3    772
1    624
4    619
2    541
0    445
Name: count, dtype: int64
Medoids después de integración (K-Medoids): [[ 1.22760437  0.29936466  0.26821535  0.33997077]
 [-0.23751423  1.25323287  0.84734789  1.20933371]
 [-0.88867805 -0.96016676 -0.77198442 -0.80812145]
 [-0.40030518 -0.15540548 -0.06626574 -0.17348599]
 [ 0.7392315  -0.93811295 -0.83872506 -0.78094923]]
Distribución de nuevos datos por cluster: Cluster
3    377
4    306
2    300
1    294
0    224
Name: count, dtype: int64
Variabilidad de los clusters (SSE): 0.0

Integración con Ext. 2
Clusters después de integración (K-Medoids): Cluster
4    1069
2    1048
0     848
1     789
3     747
Name: count, dtype: int64
Medoids después de integración (K-Medoids): [[ 0.98369992  0.41744509  0.26362003  0.45276638]
 [-0.73104448  1.36990094  1.24415045  0.94722414]
 [-0.73104448 -0.15929416 -0.07100518 -0.11919824]
 [-0.89435347 -1.03097709 -0.87951957 -0.

**ANALISIS DEL ARCHIVO**
En el archivo se realiza un análisis de clustering de Fintechs en etapas, comenzando con un clustering inicial y luego integrando nuevos datos iterativamente. Se utilizan dos algoritmos, K-Means y K-Medoids, para la agrupación, y se evalúan los resultados en cada etapa para comprender cómo la incorporación de nuevos datos afecta la estructura de los clusters.

El SSE se calcula después de cada integración de nuevos datos para ver cómo la variabilidad de los clusters se ve afectada por la incorporación de estos nuevos datos. Un aumento en el SSE después de una integración podría indicar que los nuevos datos no se ajustan bien a los clusters, mientras que un SSE que se mantiene estable podría indicar que los nuevos datos se integran bien a la estructura de los clusters.